#! /usr/bin/env bash
set -e

# dependencies
dnf -y update
dnf -y install curl git postgresql-devel sqlite-devel cyrus-sasl-devel postgresql-server postgresql postgresql-contrib sudo zlib-devel supervisor libstdc++ psmisc
dnf clean all

echo "\nDone installing dependencies...\n"
