#! /usr/bin/env bash
set -e

# dependencies
dnf update
dnf -y install curl git postgresql-devel sqlite-devel cyrus-sasl-devel postgresql-server postgresql postgresql-contrib sudo zlib-devel supervisor libstdc++ 
dnf clean

echo "\nDone installing dependencies...\n"
