#! /usr/bin/env bash
set -e

# stellar-core
wget -O stellar-core https://github.com/hard-codr/docker-stellar-core-horizon-rpi/releases/download/v0.1.0/stellar-core.aarch64
mv stellar-core /usr/local/bin
chmod a+x /usr/local/bin/stellar-core

# horizon
wget -O horizon https://github.com/hard-codr/docker-stellar-core-horizon-rpi/releases/download/v0.1.0/horizon.aarch64
mv horizon /usr/local/bin
chmod a+x /usr/local/bin/horizon

echo "\nDone installing stellar-core and horizon...\n"
